# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tejushuro.com
title: Wedding
email: hello@tejushuro.com
author: Surajit Dutta
description: Shuro and Teju are getting married. It is on 9th May this year. Mark it on your calendar. Here they come, India.
copyright: Copyright &copy; 2017 The story of our life. All Rights Reserved.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/tjsu1706
